services:
  ark-portfolio:
    image: docker.io/arkapravoghosh1/ark-portfolio:latest
    container_name: ark-portfolio
    restart: always
    ports:
      - 80:80
    networks:
      - ark-portfolio-network
networks:
  ark-portfolio-network:
    driver: bridge
