services:
  ark-portfolio:
    image: ghcr.io/arkapravo-ghosh/ark-portfolio:latest
    container_name: ark-portfolio
    restart: always
    ports:
      - 80:80
    networks:
      - ark-portfolio-network
networks:
  ark-portfolio-network:
    driver: bridge
