import {
  allSkills,
  education,
  experiences,
  featuredProjects,
  navItems,
  pageMetadata,
  personJsonLd,
  personalInfo,
  primarySocials,
  projects,
  siteConfig,
  skillCategories,
  socials,
  testimonials,
  volunteering,
  websiteJsonLd,
} from "../../src/configs";

export {
  allSkills,
  education,
  experiences,
  featuredProjects,
  navItems,
  pageMetadata,
  personJsonLd,
  personalInfo,
  primarySocials,
  projects,
  siteConfig,
  skillCategories,
  socials,
  testimonials,
  volunteering,
  websiteJsonLd,
};

export const portfolioData = {
  personalInfo,
  experiences,
  volunteering,
  education,
  projects,
  featuredProjects,
  skillCategories,
  allSkills,
  socials,
  primarySocials,
  testimonials,
  navItems,
  siteConfig,
  personJsonLd,
  websiteJsonLd,
  pageMetadata,
};
