name: Badge Creation

on:
  push:
    branches: [ main ]

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Download cloc
        run: |
          sudo apt-get update -y
          sudo apt-get install -y cloc
      - name: Get the Numbers
        run: |
          cloc .
          echo "CODE_LINES=$(./.misc/cloc.sh --loc)" >> $GITHUB_ENV
      - name: Create Lines-of-Code-Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ vars.GIST_ID }}
          gistID: ${{ secrets.BADGE_GIST_ID }}
          filename: loc.json
          label: Lines of Code
          message: ${{ env.CODE_LINES }}
          color: blue
