name: Badge Creation

on:
  push:
    branches: [ main ]

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Download cloc
        run: |
          sudo apt update
          sudo apt install -y cloc
      - name: Get the Numbers
        run: |
          echo "CODE_LINES=$(./.misc/cloc.sh --loc)" >> $GITHUB_ENV
      - name: Create Lines-of-Code-Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ vars.GIST_ID }}
          gistID: ${{ secrets.BADGE_GIST_ID }}
          filename: loc.json
          label: Lines of Code
          message: ${{ env.CODE_LINES }}
          color: blue
