name: Badge Creation

on:
  push:
    branches: [ main ]

jobs:
  update-badges:
    name: Update Badges
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download cloc
        run: |
          sudo apt update
          sudo apt install -y cloc
      - name: Check cloc version
        run: cloc --version
      - name: Print the current directory
        run: pwd
      - name: Get the Numbers
        run: |
          cloc --include-lang="JavaScript" --md . | awk -F'|' 'END { printf "%.1fk\n", $5/1000 }' | tr -d '\n'
          echo CODE_LINES=$(cloc --include-lang="JavaScript" --md . | awk -F'|' 'END { printf "%.1fk\n", $5/1000 }' | tr -d '\n') >> $GITHUB_ENV
      - name: Create Lines-of-Code-Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.GIST_SECRET }}
          gistID: ${{ vars.GIST_ID }}
          filename: loc.json
          label: Lines of Code
          message: ${{ env.CODE_LINES }}
          color: blue
